# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true

r:
  - oldrel
  - release
  - devel

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

repos:
  docker: http://r.docker.stat.auckland.ac.nz/R

addons:
  apt:
    update: true
    packages:
      - xvfb
      - libgtk2.0-dev
      - xorg-dev
      - libxml2-dev
      - libnlopt-dev

