# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: xenial
language: R
sudo: true
cache:
  - packages
  - directories:
    - $HOME/Library/Caches/Homebrew
latex: false
pandoc: false
services:
  - xvfb

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
    - _R_CHECK_SYSTEM_CLOCK_=FALSE

repos:
  docker: https://r.docker.stat.auckland.ac.nz

r_github_packages:
  - jverzani/gWidgets2RGtk2
  - iNZightVIT/iNZightModules@dev
  - iNZightVIT/iNZightPlots@dev
  - iNZightVIT/iNZightTools@dev

addons:
  apt:
    update: true
    packages:
      - libgtk2.0-dev
      - xorg-dev
      - libxml2-dev
      - libnlopt-dev
      # - r-cran-rodbc
      # - r-cran-rgtk2
      # - r-cran-cairodevice

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      sudo chown -R $(whoami) /usr/local/share;
      curl -L http://mac.r-project.org/libs/GTK_2.24.17-X11.pkg -o gtk.pkg;
      sudo installer -pkg gtk.pkg -target / -allowUntrusted;
      rm gtk.pkg;
      mkdir ~/Documents/iNZightVIT;
    fi

after_success:
  - Rscript -e 'covr::codecov()'

before_cache:
  - brew cleanup
